# Final Production Deployment Configuration
# Docker + Cron Service Architecture for Andalan ATK Backend Export Automation

services:
- type: cron
  name: andalan-atk-automation-final-json-fix
  schedule: "0 3,11,15 * * *"  # 10:00 AM, 6:00 PM & 10:00 PM WIB (03:00, 11:00 & 15:00 UTC)
  dockerfilePath: ./Dockerfile
  dockerContext: .

  # Environment Variables - Production Configuration
  envVars:
  - key: TELEGRAM_TOKEN
    value: "7617892433:AAHrMesr-6MosGqMq5z0JVxFKa61ZAr_abM"
  - key: TELEGRAM_CHAT_ID
    value: "-4924885979"
  - key: DISABLE_NOTIFICATIONS
    value: "false"  # Enable notifications in production
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: DISPLAY
    value: ":99"
  - key: CHROME_BIN
    value: "/usr/bin/google-chrome-stable"
  - key: CHROME_PATH
    value: "/usr/bin/google-chrome-stable"
  - key: TZ
    value: "Asia/Jakarta"

  # Health check disabled for cron jobs (not applicable)
  # Resource optimization for cloud environment