services:
  - type: cron
    name: automation-bot-2x-daily
    env: python
    plan: starter
    pythonVersion: "3.11.9"
    schedule: "0 1,11 * * *"  # 8 AM & 6 PM WIB (1 AM & 11 AM UTC)
    buildCommand: |
      python --version
      pip install --no-cache-dir numpy==1.24.4
      pip install --no-cache-dir -r requirements.txt
      apt-get update && apt-get install -y wget gnupg
      python -m playwright install-deps
      python -m playwright install
      which chromium-browser || echo "Chromium not found in PATH"
      ls -la /opt/render/.cache/ms-playwright/ || echo "Playwright cache not found"
    startCommand: |
      export TZ=Asia/Jakarta
      echo "Checking for Playwright browsers..."
      python -c "from playwright.sync_api import sync_playwright; sync_playwright().start()" || python -m playwright install chromium
      python main_scheduler.py --all --headless --production --single-session
    # Environment variables must be set in Render.com dashboard:
    # BACKEND_USERNAME, BACKEND_PASSWORD, TELEGRAM_TOKEN, TELEGRAM_CHAT_ID
    envVars:
      - key: HEADLESS
        value: "true"
      - key: TZ
        value: "Asia/Jakarta"
      - key: PYTHONUNBUFFERED
        value: "1"