services:
  - type: cron
    name: automation-bot-2x-daily
    env: python
    plan: starter
    pythonVersion: "3.11.9"
    schedule: "0 1,11 * * *"  # 8 AM & 6 PM WIB (1 AM & 11 AM UTC)
    buildCommand: |
      python --version
      pip install --no-cache-dir numpy==1.24.4
      pip install --no-cache-dir -r requirements.txt
      apt-get update
      apt-get install -y wget unzip curl xvfb
      wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y /tmp/chrome.deb
      rm -f /tmp/chrome.deb
      apt-get install -yf
      which google-chrome-stable || echo "Chrome not found after installation"
      google-chrome-stable --version || echo "Chrome version check failed"
      google-chrome-stable --headless --no-sandbox --disable-gpu --dump-dom https://www.google.com > /dev/null && echo "Chrome headless test successful" || echo "Chrome headless test failed"
    startCommand: |
      export TZ=Asia/Jakarta
      echo "Starting automation with Selenium WebDriver..."
      google-chrome-stable --version || echo "Chrome not available"
      which google-chrome-stable && echo "Chrome found at: $(which google-chrome-stable)" || echo "Chrome not found"
      python main_scheduler.py --all --headless --production --single-session
    # Environment variables must be set in Render.com dashboard:
    # BACKEND_USERNAME, BACKEND_PASSWORD, TELEGRAM_TOKEN, TELEGRAM_CHAT_ID
    envVars:
      - key: HEADLESS
        value: "true"
      - key: TZ
        value: "Asia/Jakarta"
      - key: PYTHONUNBUFFERED
        value: "1"