services:
  - type: cron
    name: automation-bot-2x-daily
    env: python
    plan: starter
    pythonVersion: "3.11.9"
    schedule: "0 1,11 * * *"  # 8 AM & 6 PM WIB (1 AM & 11 AM UTC)
    buildCommand: |
      python --version
      pip install --no-cache-dir numpy==1.24.4
      pip install --no-cache-dir -r requirements.txt
      apt-get update && apt-get install -y wget gnupg unzip
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      apt-get update && apt-get install -y google-chrome-stable
      which google-chrome || echo "Chrome not found in PATH"
      google-chrome --version || echo "Chrome version check failed"
    startCommand: |
      export TZ=Asia/Jakarta
      echo "Starting automation with Selenium WebDriver..."
      google-chrome --version
      python main_scheduler.py --all --headless --production --single-session
    # Environment variables must be set in Render.com dashboard:
    # BACKEND_USERNAME, BACKEND_PASSWORD, TELEGRAM_TOKEN, TELEGRAM_CHAT_ID
    envVars:
      - key: HEADLESS
        value: "true"
      - key: TZ
        value: "Asia/Jakarta"
      - key: PYTHONUNBUFFERED
        value: "1"